[project]
name = "multi-doc-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.12.0",
    "from-root>=1.3.0",
    "ipykernel>=7.0.1",
    "langchain-groq>=1.0.0",
    "langchain-mistralai>=1.0.1",
]
