embedding_model:
  provider: "mistral"
  model_name: "mistral-embed"

retriever:
  top_k: 10
  search_type: "mmr"  # Options: "similarity", "mmr", "similarity_score_threshold"
  # MMR (Maximal Marginal Relevance) parameters for diverse results
  fetch_k: 20  # Number of documents to fetch before MMR re-ranking (should be > top_k)
  lambda_mult: 0.5  # Diversity vs relevance (0=max diversity, 1=max relevance)

llm:
  mistral:
    provider: "mistral"
    model_name: "mistral-large-latest"
    temperature: 0
    max_output_tokens: 2048

